# set default elastic version to 6.1.1
ARG ELASTIC_VESRSION=6.1.1

# https://github.com/elastic/kibana-docker
FROM docker.elastic.co/kibana/kibana-x-pack:${ELASTIC_VESRSION}

# Add your kibana plugins setup here
# Example: RUN kibana-plugin install <name|url>
