# set default elastic version to 6.1.1
ARG ELASTIC_VESRSION=6.1.1

# https://github.com/elastic/elasticsearch-docker
FROM docker.elastic.co/elasticsearch/elasticsearch-basic:$ELASTIC_VESRSION

# Add your elasticsearch plugins setup here
# Example: RUN elasticsearch-plugin install analysis-icu
