# set default elastic version to 6.1.1
ARG ELASTIC_VESRSION=6.1.1

# https://github.com/elastic/logstash-docker
FROM docker.elastic.co/logstash/logstash-x-pack:${ELASTIC_VESRSION}

# Add your logstash plugins setup here
# Example: RUN logstash-plugin install logstash-filter-json
